name: maven-publish-action
author: Wasiq Bhamla
description: GitHub Action for automatically publishing to Maven Central
inputs:
  gpg_private_key:
    description: GPG private key for signing the published artifacts
    required: false
  gpg_passphrase:
    description: Passphrase for the GPG key
    required: false
  server_username:
    description: Username for your repository manager account
    required: true
  server_password:
    description: Password for your Nexus account
    required: true
  server_id:
    description: Server ID of the repository management server
    required: false
    default: ossrh
  directory:
    description: Directory of the Maven project which should be deployed
    required: false
  pom_file_name:
    description: POM file name
    required: false
  settings_path:
    description: Directory path for Maven settings file
    required: false
  maven_goals_phases:
    description: Maven goals and build phases to execute
    required: false
    default: clean deploy
  maven_args:
    description: Additional arguments to pass to the Maven command
    required: false
    default: ''
  maven_profiles:
    description: Active Maven profiles
    required: false
    default: deploy
runs:
  using: node20
  main: dist/index.js
branding:
  icon: upload-cloud
  color: blue
