name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  is-dependabot-runner:
    runs-on: ubuntu-latest

    outputs:
      env-present: ${{ steps.env-key.outputs.present }}

    steps:
      - name: Check BrowserStack secrets presence
        id: env-key
        shell: bash
        run: |
          if [ "$NEXUS_USERNAME" == "" ]; then
            echo "present=NO" >> $GITHUB_OUTPUT
          else
            echo "present=YES" >> $GITHUB_OUTPUT
          fi

  test:
    needs: is-dependabot-runner

    if: (github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name) && needs.is-dependabot-runner.outputs.env-present == 'YES'

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm add -g @vercel/ncc
          pnpm install && pnpm bundle

      - name: Run Test
        run: pnpm test
