name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
  CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  check-env-key:
    runs-on: ubuntu-latest

    outputs:
      env-present: ${{ steps.env-key.outputs.present }}

    steps:
      - name: Check Environment variable
        id: env-key
        shell: bash
        run: |
          if [ "$NEXUS_USERNAME" == "" ]; then
            echo "present=NO" >> $GITHUB_OUTPUT
          else
            echo "present=YES" >> $GITHUB_OUTPUT
          fi

  test:
    needs: check-env-key
    name: Test Action

    if: (github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name) && needs.check-env-key.outputs.env-present == 'YES'

    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm add -g @vercel/ncc
          pnpm install && pnpm bundle

      - name: Run Test
        run: pnpm test

  test-workflow:
    needs: test
    name: Test Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm add -g @vercel/ncc
          pnpm install && pnpm bundle

      - name: Check the workflow for Nexus
        id: test-action-nexus
        uses: ./
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ env.GPG_PASSPHRASE }}
          server_username: ${{ env.NEXUS_USERNAME }}
          server_password: ${{ env.NEXUS_PASSWORD }}
          maven_profiles: deploy
          server_id: ossrh
          directory: ${{ github.workspace }}/java-test/nexus/with-gpg
          maven_args: -DskipTests -Dcheckstyle.skip

      - name: Check the workflow for Central
        id: test-action-central
        uses: ./
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ env.GPG_PASSPHRASE }}
          server_username: ${{ env.CENTRAL_USERNAME }}
          server_password: ${{ env.CENTRAL_PASSWORD }}
          maven_profiles: release
          server_id: central
          directory: ${{ github.workspace }}/java-test/central
          maven_args: -DskipTests -Dcheckstyle.skip

      - name: Print Nexus Output
        id: output-nexus
        run: echo "${{ steps.test-action-nexus.outputs.published }}"

      - name: Print Nexus Output
        id: output-central
        run: echo "${{ steps.test-action-central.outputs.published }}"
